services:
  scylla:
    image: scylladb/scylla:5.2
    container_name: user-service-scylla
    ports:
      - "9042:9042"      # CQL native transport
    volumes:
      - scylla-data:/var/lib/scylla
    command: --smp 1 --memory 1G --overprovisioned 1
    healthcheck:
      test: ["CMD", "cqlsh","-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  scylla-data:

  